[package]
name = "sanitize-filename"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_bindgen = "0.5.1"
once_cell = "1.13.0"
regex = "1.6.0"

[lib]
name = "snaitize"
crate-type = ["cdylib"]