[package]
name = "rs_lib"
version = "0.0.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"

[dependencies]
once_cell = "1.13.0"
regex = "1.6.0"
wasm-bindgen = "=0.2.81"
